name: softmol
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - openbabel
  - rdkit
  - pip:
      - numpy==1.26.4
      - torch==2.8.0
      - torchvision==0.23.0
      - torchmetrics==1.6.2
      - datasets==3.3.2
      - einops==0.8.1
      - fsspec==2024.2.0
      - git-lfs==1.6
      - hydra-core==1.3.2
      - lightning==2.5.0.post0
      - notebook==7.2.2
      - nvitop==1.3.2
      - omegaconf==2.3.0
      - packaging==23.2
      - pandas==2.2.1
      - PyTDC
      - rich==13.7.1
      - scikit-learn==1.5.1
      - timm==0.9.16
      - tokenizers==0.21.0
      - tqdm==4.67.1
      - transformers==4.49.0
      - triton==3.4.0
      - wandb==0.19.8
